name: Auto-generate sitemap

on:
  push:
    paths:
      - 'OJapp/shop/**'     # 商品追加・更新時に自動実行
      - 'OJapp/**.html'
  schedule:
    - cron: '0 18 * * *'     # 毎日AM3:00(JST) に自動実行
  workflow_dispatch:          # 手動実行もOK

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > OJapp/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> OJapp/sitemap.xml

          # OJappトップ固定
          echo '  <url><loc>https://github.ojach.com/OJapp/</loc></url>' >> OJapp/sitemap.xml

          # OJapp 配下すべての HTML を追加（shop も含む）
          find OJapp -name "*.html" | while read file; do
            url="https://github.ojach.com/${file}"
            url=${url//OJapp\//OJapp/}  # パス整形
            echo "  <url><loc>${url}</loc></url>" >> OJapp/sitemap.xml
          done

          echo '</urlset>' >> OJapp/sitemap.xml

      - name: Commit sitemap
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add OJapp/sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
